version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/app
      - node-modules-volume:/usr/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend/api:/usr/app

  sql:
    build:
      context: ./backend/sql
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
      - ./backend/sql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    tty: true

volumes:
  node-modules-volume: