version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/app
    environment:
      - PORT=3000

  backend:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend/api:/usr/app

  sql:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sample_db
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
    volumes:
      - ./backend/sql/data:/var/lib/mysql
      - ./backend/sql/cnf:/etc/mysql/conf.d
      - ./backend/sql/log:/usr/local/mysql/data
    ports:
      - 3308:3308
    command: >
          bash -c "
          chmod 644 /etc/mysql/conf.d/*.cnf
          && /entrypoint.sh mysqld --port 3308
          "
    tty: true
